#!/bin/bash

# IT Help Desk Voice Bot - Run Instructions

echo "🚀 IT Help Desk Voice Bot - Deployment & Run Guide"
echo ""
echo "First, make sure you have all API keys set up:"
echo "- LiveKit Cloud credentials"
echo "- Deepgram API key (STT)"
echo "- OpenAI API key (LLM)" 
echo "- Cartesia API key (TTS)"
echo ""
echo "See DEPLOYMENT_GUIDE.md for detailed instructions"
echo ""
echo "🔧 DEPLOYMENT OPTIONS:"
echo ""
echo "Option 1 - Deploy to LiveKit Cloud (Recommended):"
echo "1. cd backend"
echo "2. lk cloud auth"
echo "3. lk agent create"
echo "4. Test at: https://agents.livekit.io/"
echo ""
echo "Option 2 - Local Development:"
echo "Terminal 1: cd backend && source venv/bin/activate && python run_server.py"
echo "Terminal 2: cd frontend && npm run dev"
echo "Terminal 3: cd backend && source venv/bin/activate && python agent.py dev"
echo ""
echo "🌐 Playground: https://agents.livekit.io/"
echo "📚 Full Guide: DEPLOYMENT_GUIDE.md"